### ISSUE TITLE
Proto Plus messages are not pickleable

### ISSUE THREAD

**Issue by busunkim96** [googleapis/proto-plus-python#162]
From https://github.com/googleapis/python-iot/issues/42

```py
class Composer(proto.Message):
    given_name = proto.Field(proto.STRING, number=1)
    family_name = proto.Field(proto.STRING, number=2)

composer = Composer(given_name="Johannes", family_name="Bach")
pickled_composer = pickle.dumps(composer)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class 'Composer'>: it's not the same object as __main__.Composer
```

The current recommendation is to serialize to bytes. https://proto-plus-python.readthedocs.io/en/latest/reference/message.html

**Comment by software-dov** [comment]
The preferred serialization mechanism is the `serialize` class method.
Given the example message definition above, serialize and deserialize like so:
```python
composer = Composer(given_name="Richard", family_name="Strauss")
composer_bytes = Composer.serialize(composer)
composer2 = Composer.deserialize(composer_bytes)
```

If using something like `multiprocessing.Pool.map`, the suggested pattern is something like this:
```python
from multiprocessing import Pool

with Pool(5) as p:
    def process_bach(bach_bytes):
        bach = Composer.deserialize(bach_bytes)
        return Composer.serialize(get_parent(bach))

    initial_bachs = [Composer(given_name=name, family_name="Bach") for name in ["Johann Sebastian", "Carl Philipp", "Johann Christian", "Wilhelm Friedemann", "Johann Friedrich"]]
    child_bachs = [Composer.deserialize(bytes) for bytes in p.map(process_bach, (Composer.serialize(bach) for bach in initial_bachs))]
```

**Comment by tseaver** [comment]
@software-dov This issue is a major blocker for integrating current Bigtable (2.4.x) with Apache Beam, which relies on pickling messages across hosts / processes.  See e.g. [this CI failure](https://source.cloud.google.com/results/invocations/a732cc40-d3a4-4ecd-af91-986b2f773476/targets/github%2Fpython-bigtable%2Fsamples%2Fbeam/tests).  We could solve the issue by writing `__getstate__` and `__setstate__` for `proto.Message` which just used the same format as `serialize`.
