### ISSUE TITLE
to_json option to exclude newline

### ISSUE THREAD

**Issue by yiga2** [googleapis/proto-plus-python#284]
The `to_json` result always pretty-prints, meaning newlines are always inserted. This makes the result unusable with apps expecting newline-delimited JSON, that is, strict json w/o formatting (no LF, tabs,...). 
Our use case is BigQuery which treats newlines as record-separator, and trying to read a `to-json` file or record returns `key not found`.

Request:
There should be an option to output the result without formatting, no newlines or tabs.

Workaround:
use `to_dict` and use json module to correctly convert.

**Comment by vam-google** [comment]
Hi @yiga2, 
Thanks for your request. This should be addressed in  https://github.com/googleapis/proto-plus-python/pull/336

**Comment by yiga2** [comment]
I don't understand how it fixes the issue at hand. The indenting is one thing but the newlines still are added.
I had expected a `pretty-print` boolean instead (defaulting to True).
As said, `to_dict()` and jsonifying ourself worked for us so you can close if you wish.

**Comment by vam-google** [comment]
New lines are not added, because this whole thing eventually goes to `json.dumps()` call, and the indent parameter gets propagated there unmodified.

The call goes like this:
```
proto.MessageMeta.to_json(indent) -> 
    google.protobuf.json_format.MessageToJson(indent) -> 
       google.protobuf.json_format._Printer().ToJsonString(indent) -> 
          json.dumps(indent)
```
Here is what `json.dumps(indent)` documentation says:
```
    If ``indent`` is a non-negative integer, then JSON array elements and
    object members will be pretty-printed with that indent level. An indent
    level of 0 will only insert newlines. ``None`` is the most compact
    representation.
```

This is also how the added test tests it (it calls `indent=None`). 

`to_dict()` workaround is too inefficient to be ok, especially given that the fix is super simple and it should have been done like that in the first iteration of `to_json()`  method.
