### ISSUE TITLE
"proto" is too generic name for a top level package 

### ISSUE THREAD

**Issue by eyalfink** [googleapis/proto-plus-python#79]
All of the google APIs are under google module.
protobuf package it self is under google.protobuf

This package, and now the google APIs which start using it, breaks all repositories which have an internal package named proto. Specifically, it is not uncommon to place generated protobuf classes under proto directory.

I believe that naming this package "proto" is wrong and not consistent with all other packages within the google api world.

**Comment by software-dov** [comment]
Some historical context:
proto-plus started out as a side project that was not officially endorsed by Google. Making the module live under the 'google' namespace did not make sense at the time. It is not maintained by the same team as google.protobuf, so keeping it under that namespace would have been misleading and may have also lead to name collisions.

Can you elaborate a little on your use case? Having both generated protos and proto-plus defined message types seems like a niche interaction.

**Comment by eyalfink** [comment]
We are working with a "single repo" approach where we have .proto files placed all over the source tree (placed inside the module using them). Our [build system](https://github.com/resonai/ybt), uses protoc to compile the .proto and put the generated code under a parallel source tree which root name is "proto" so imports in the code will look like
```
import proto.path.to.my.package.foo_pb2.py
```
and we add the generated code directory to the PYTHONPATH

I believe that this pattern is quite similar to what blaze does and what many "single repo" companies are doing.

The interaction with proto-plus happened few days ago when we picked up version 2.0.0 of Google's official 
[google-cloud-container](https://github.com/googleapis/python-container) package which uses proto-plus and does
[import proto](https://github.com/googleapis/python-container/blob/master/google/cloud/container_v1/types/cluster_service.py#L18 )

Which doesn't play well with our PYTHONPATH :-(

**Comment by software-dov** [comment]
Does it work to differentiate the imports using `from .proto` with the dot?
@crwilcox knows more about Python import semantics.

**Comment by eyalfink** [comment]
using ```import .proto``` will solve the problem for people which have an internal directory named ```proto```  but not for people like me with a proto directory at the root of their repo.

Note that even for people with internal proto dir, if they have code which uses the ```import proto``` notation the latest version of google-cloud-container will break their code because of the use of this package (they have a simple solution but yet the code will break)

**Comment by crwilcox** [comment]
@eyalfink I want to be super clear here with how behavior is happening, since it could very much impact how we fix this.

In your environment, when the google-cloud-container `import proto` is evaluated what is that attempting to import? I believe it is importing your `proto` package from the description? As in your proto package is earlier on the path.

**Comment by eyalfink** [comment]
Exactly, My PYTHONPATH is set to ```.:build/gen/``` and my code run for the directory of the code and under build/gen/proto the generated *_pb2.py code are located.

python look there before looking in the system installed packages. 
So when a package using proto-plus is doing ```import proto``` it catches my proto package instead of the one your package which is installed on the system.

**Comment by crwilcox** [comment]
@software-dov it sounds like we may be able to fix this by leaving `import proto` for folks currently using (alias the package there) but maybe move to calling our package `protoplus` or `proto_plus`? I personally like the first, but not a highly weighted vote really. This would resolve @eyalfink issue while also not breaking existing users.

Could also make all of it `from protoplus import proto`. *shrugs*

We could eventually remove it as well of course.

**Comment by software-dov** [comment]
Not breaking existing users + solving a real-world user problem + a slightly more descriptive name; this is a course of action I fully support, and I agree that the moniker `protoplus` is fine.
I, personally, have little idea how to _do_ this; I'm guessing it's something clever involving subpackages or namespace packages...? I'll try some stuff, but I will probably wind up asking you for help.

**Comment by hkdevandla** [comment]
Making this as a feature request for now. @software-dov , lets us consider this as part of next sprint planning.

**Comment by 0x2b3bfa0** [comment]
Just another opinion here: `proto` is fine for me, even if it's too generic, but `protocolbuffers` would make me happy; it's descriptive, consistent, unique and memorable.

```python
import protocolbuffers
```

```python
import protocolbuffers as proto  # If you deem it too long
```

```python
from protocolbuffers import Message, Enum  # If you don't have any name clash
```

**Comment by indragiek** [comment]
Adding a +1 here for the problem @eyalfink is describing, we have this exact problem with our Bazel repository that has a top level `proto` directory containing all of our protobuf targets. 

Bazel expects us to import these as `import proto.foo`in Python -- the `proto` package in this case is a namespace package as defined in PEP 420, and this package (which is also `proto`, but is a regular package rather than a namespace package) takes precedence over our namespace package no matter what the order of the paths in `PYTHONPATH` is.

We discovered this issue not because we were using `proto-plus` directly, but because the latest versions of the `google-cloud-logging` and `google-cloud-error-reporting` libraries depend on this one. There are no easy workarounds for this problem besides renaming our `proto` directory and consequently all of our Bazel proto targets.

Would really appreciate having this be renamed to something that won't easily conflict with a common name.

**Comment by tmc** [comment]
Would love to see movement here, "protoplus" seems quite sensible.

**Comment by parthea** [comment]
This would result in a breaking change for users. I'm going to close this issue as we're not prepared to introduce a breaking change.
